### ISSUE TITLE
Plugin prevents execution of other event handlers on the payment form

### ISSUE THREAD

**Issue by SeifertDaniel** [FATCHIP-GmbH/OXID-Klarna-6#58]
Due to the special form handling with the payment data on the this page, the Klarna module globally intercepts the click event on the submit button, prevents its further execution (event.preventDefault()) and handles this in its own logic (in tcklarna_payments_handler.js). For all non-Klarna cases (e.g. payment types of the Unzer module) the form is submitted manually with $form.submit().

With such manual triggers, however, no event handlers take effect that are supposed to handle the submit event on the form element. In the case of Unzer, however, the handling logic is there, which cannot be executed in combination with the Klarna module and thus leads to errors.

The solution could be that event.preventDefault() is only executed if the selected payment type is clearly to be processed by Klarna. All other payment types must remain unhandled (no manual triggering either).

**Comment by FATCHIP-GmbH** [comment]
This is fixed with https://github.com/FATCHIP-GmbH/OXID-Klarna-6/commit/761d3cdcdb9030dd126304daddf598270d608495
